backend:
  name: github
  repo: notahpspell/canismajor   # <- your repo
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://rbasnet.com"

collections:
  - name: "posts"
    label: "Blog Posts"
    label_singular: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "Custom Slug (optional)", widget: "string", required: false }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "description", label: "Short Description", widget: "text" }
      - { name: "featured_image", label: "Featured Image", widget: "image", required: false }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - { name: "bod
